on:
  release:
    types:
      - published
  workflow_dispatch:

name: release-build&push-mainRepo

jobs:
  build:
    name: Release - Build and push docs to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Antora
        run: npm install

      - name: Generate Site
        run: npx antora --fetch antora-playbook.yml

      - name: Unzip archive
        run: unzip build/site.zip -d build/site

      - name: Remove archive
        run: rm build/site.zip

      - name: Push to github-pages branch on zot-site
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'build/site'
          destination-github-username: 'project-zot'
          destination-repository-name: 'project-zot.github.io'
          user-email: rchincha@cisco.com
          target-branch: main
          target-directory: docs
